-- ============================================================
--  BIBLIOTECA DE NOTAS AROMÁTICAS — DRC SCENTS
--  Nombres extraídos de las familias olfativas de Fragrantica.
--  Las imágenes las agregas tú desde el panel (pestaña "Notas").
--
--  CÓMO USAR: Supabase -> SQL Editor -> New query -> pega esto -> Run.
--  Es SEGURO correrlo varias veces: no crea duplicados por nombre.
-- ============================================================

insert into notas (nombre)
select v.nombre
from (values
  ('Bergamota'),
  ('Limón'),
  ('Naranja'),
  ('Mandarina'),
  ('Lima'),
  ('Toronja'),
  ('Pomelo'),
  ('Yuzu'),
  ('Hassaku'),
  ('Verbena'),
  ('Hierba limón'),
  ('Petit grain'),
  ('Neroli'),
  ('Durazno'),
  ('Ciruela'),
  ('Higo'),
  ('Coco'),
  ('Piña'),
  ('Rábano'),
  ('Tomate'),
  ('Pepino'),
  ('Iris'),
  ('Almendra'),
  ('Cacahuate'),
  ('Avellana'),
  ('Rosa'),
  ('Jazmín'),
  ('Ylang-ylang'),
  ('Heliotropo'),
  ('Nardo'),
  ('Osmanto'),
  ('Magnolia'),
  ('Lavanda'),
  ('Violeta'),
  ('Peonía'),
  ('Fresia'),
  ('Lirio de los valles'),
  ('Mimosa'),
  ('Junquillo'),
  ('Narciso'),
  ('Jacinto'),
  ('Retama'),
  ('Siempreviva'),
  ('Cempasúchil'),
  ('Flor de loto'),
  ('Nenúfar'),
  ('Azahar'),
  ('Gardenia'),
  ('Frangipani'),
  ('Madreselva'),
  ('Gálbano'),
  ('Hoja de higuera'),
  ('Hoja de tomate'),
  ('Té verde'),
  ('Té negro'),
  ('Romero'),
  ('Tomillo'),
  ('Menta'),
  ('Estragón'),
  ('Mejorana'),
  ('Hinojo'),
  ('Albahaca'),
  ('Salvia'),
  ('Anís'),
  ('Ajenjo'),
  ('Cálamo'),
  ('Angélica'),
  ('Espicanardo'),
  ('Cumarina'),
  ('Helecho'),
  ('Canela'),
  ('Pimienta negra'),
  ('Pimienta rosa'),
  ('Clavo de olor'),
  ('Cilantro'),
  ('Jengibre'),
  ('Azafrán'),
  ('Tamarindo'),
  ('Alcaravea'),
  ('Orégano'),
  ('Cardamomo'),
  ('Nuez moscada'),
  ('Vainilla'),
  ('Chocolate'),
  ('Cacao'),
  ('Caramelo'),
  ('Nougat'),
  ('Crème brûlée'),
  ('Algodón de azúcar'),
  ('Café'),
  ('Miel'),
  ('Sándalo'),
  ('Cedro'),
  ('Oud'),
  ('Vetiver'),
  ('Pachulí'),
  ('Palisandro'),
  ('Pino'),
  ('Abeto'),
  ('Jacarandá'),
  ('Musgo de roble'),
  ('Musgo de árbol'),
  ('Benjuí'),
  ('Bálsamo de Perú'),
  ('Bálsamo de Tolú'),
  ('Opopónaco'),
  ('Incienso'),
  ('Mirra'),
  ('Alquitrán de abedul'),
  ('Elemí'),
  ('Styrax'),
  ('Almizcle'),
  ('Ámbar'),
  ('Ámbar gris'),
  ('Castóreo'),
  ('Civeta'),
  ('Cuero'),
  ('Gamuza'),
  ('Semillas de ambreta'),
  ('Cera de abeja'),
  ('Leche'),
  ('Champán'),
  ('Piña colada'),
  ('Ginebra'),
  ('Enebro'),
  ('Vino'),
  ('Talco'),
  ('Notas terrosas')
) as v(nombre)
where not exists (
  select 1 from notas n where lower(n.nombre) = lower(v.nombre)
);

-- Notas insertadas: 128
